### ISSUE TITLE
undefined method 'find' after upgrading from 0.12.1 to 0.14.1

### ISSUE THREAD

**Issue by nicolo** [thoughtbot/capybara-webkit#461]
After upgrading from capybara 0.12.1 to 0.14.1 it errors out any time I try to call find.
example:
find('#my_id')

throws
undefined method `find' for #RSpec::Core::ExampleGroup::Nested_1::Nested_1:0x007f92f9619f48
